#version: "3.9"  Obsolete, use 3.8
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: grc_user
      POSTGRES_PASSWORD: grc_pass
      POSTGRES_DB: grc_dashboard
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: ../backend
    env_file:
      - ../.env          # holds VT_API_KEY + DB creds
    depends_on:
      - db
    ports:
      - "8181:8181"
  # optional nice-to-have
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      # Disable validation of email domains if needed
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
  