name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: grc_user
          POSTGRES_PASSWORD: grc_pass
          POSTGRES_DB: grc_dashboard
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U grc_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r backend/requirements.txt pytest
      - run: pytest -q
